name: Gradle build

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest ]
    runs-on: ${{matrix.os}}
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 11
          distribution: liberica
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build
        run: ./gradlew build --build-cache --no-daemon --stacktrace
