name: Gradle build

on: [ push ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install libgsl-dev
        run: sudo apt install libgsl-dev
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            **/.gradle
            **/build
          key: gradle_6_6_1
          restore-keys: gradle_6_6_1

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-linux-1.4.20-eap-37
          key: ${{ runner.os }}-konan-1.4.20-eap-37
          restore-keys: ${{ runner.os }}-konan-1.4.20-eap-37
      - name: Build with Gradle
        run: sudo ./gradlew -Dorg.gradle.daemon=false --build-cache :kmath-gsl:cinteropLibgslNative build
  build-osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install gsl
        run: brew install gsl
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            **/.gradle
            **/build
          key: gradle_6_6_1
          restore-keys: gradle_6_6_1

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-macos-1.4.20-eap-37
          key: ${{ runner.os }}-konan-1.4.20-eap-37
          restore-keys: ${{ runner.os }}-konan-1.4.20-eap-37
      - name: Build with Gradle
        run: sudo ./gradlew -Dorg.gradle.daemon=false --build-cache :kmath-gsl:cinteropLibgslNative build

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Add msys to path
        run: SETX PATH "%PATH%;C:\msys64\mingw64\bin"
      - name: Cache gradle
        uses: actions/cache@v2
        with:
          path: |
            **/.gradle
            **/build
          key: gradle_6_6_1
          restore-keys: gradle_6_6_1

      - name: Cache konan
        uses: actions/cache@v2
        with:
          path: |
            ~/.konan/dependencies
            ~/.konan/kotlin-native-prebuilt-mingw-1.4.20-eap-37
          key: ${{ runner.os }}-konan-1.4.20-eap-37
          restore-keys: ${{ runner.os }}-konan-1.4.20-eap-37
      - name: Build with Gradle
        run: ./gradlew --build-cache build
