name: Dokka publication

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-java@v3.0.0
        with:
          java-version: 11
          distribution: liberica
      - name: Cache gradle
        uses: actions/cache@v3.0.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v3.0.1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: ./gradlew dokkaHtmlMultiModule --build-cache --no-daemon --no-parallel --stacktrace
      - uses: JamesIves/github-pages-deploy-action@4.2.5
        with:
          branch: gh-pages
          folder: build/dokka/htmlMultiModule
