name: Gradle publish

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  publish:
    environment:
      name: publish
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-java@v3.0.0
        with:
          java-version: 11
          distribution: liberica
      - name: Cache gradle
        uses: actions/cache@v3.0.1
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache konan
        uses: actions/cache@v3.0.1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/wrapper-validation-action@v1.0.4
      - name: Publish Windows Artifacts
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: >
          ./gradlew releaseAll --no-daemon --build-cache -Ppublishing.enabled=true
          -Ppublishing.space.user=${{ secrets.SPACE_APP_ID }}
          -Ppublishing.space.token=${{ secrets.SPACE_APP_SECRET }}
      - name: Publish Mac Artifacts
        if: matrix.os == 'macOS-latest'
        run: >
          ./gradlew releaseMacosX64 releaseIosArm64 releaseIosX64 release --no-daemon --build-cache
          -Ppublishing.enabled=true -Ppublishing.space.user=${{ secrets.SPACE_APP_ID }}
          -Ppublishing.space.token=${{ secrets.SPACE_APP_SECRET }}
